### ISSUE TITLE
document adding a blog

### ISSUE THREAD

**Issue by binyamin** [binyamin/eleventy-garden#16]
see #10; h/t @rosieCampbell

**Comment by Agencye** [comment]
One’s life would be completely out of mess thus eradicating all the depression and frustrations through the enticing session of exotic love spend under the influence of _**[Noida Escorts]([url](https://www.noida-escort.com)**

**Comment by henrybigbuds** [comment]
https://premiumcookies.shop/product/order-honey-bun-pre-roll-online/

**Comment by binyamin** [comment]
As per https://github.com/binyamin/eleventy-garden/discussions/71#discussion-3765981, I'm considering this one "out of scope".
