### ISSUE TITLE
Page shifting when hover over backlink

### ISSUE THREAD

**Issue by jarodise** [binyamin/eleventy-garden#19]
Hi, thanks for building this SSG template for digital gardening, I really like it. I found a small bug, It's very easy to reproduce and happens 100% of the time: 
On the demo site, simply go to notes page, click on "easter egg" and then in the backlink section, when you hover over"Notes" the whole page will shift position when the preview pops up, creating a effect as if the page is shaking. 
I think it happens because the scroll bar shows up during the hover.
Hope this can be fixed in the future iteration, thanks again! 

Jarod

**Comment by b3u** [comment]
@jarodise Hey, thanks so much for the feedback.

I was able to reproduce the bug you found. I think that there are some areas where the mouse is only half in the hover zone. That might be why it the scrollbar keeps disappearing. Thanks again for the issue.

**Comment by jarodise** [comment]
Hi, seems like the problem still exists.

**Comment by binyamin** [comment]
Same situation?

**Comment by jarodise** [comment]
Yeah, basically it's caused by the scroll bar showing up during the hovering, scroll bar is hidden by default and shows up when the hover popup goes below the bottom of the page.

**Comment by jarodise** [comment]
I think the easy solution would be either complete hide the scroll bar or make it show all the time.

**Comment by binyamin** [comment]
> I think the easy solution would be either complete hide the scroll bar or make it show all the time.

I notice that when I hover over the link, the footer shifts down as well. The modalset to `position: relative`, so when it comes appears it affects the page length. Setting it to` position: absolute` should fix this.

**Comment by binyamin** [comment]
@jarodise Try it now.

**Comment by jarodise** [comment]
I'm not sure if you pushed the update to your demo site, but from my end, the problem still persists, see the screen capture: 

![Kapture 2020-08-14 at 12 00 01](https://user-images.githubusercontent.com/15899808/90274328-f98ac980-de25-11ea-82c1-7ab2671335f1.gif)

**Comment by binyamin** [comment]
Weird. What's your screen size? What device?

**Comment by jarodise** [comment]
I'm on Macbook Pro 13 inch Late 2015, however, I don't think it's device relevant, like I said earlier, the problem is caused by scrollbar showing up when the popup goes beyond the extend of the page bottom, so as long as the content is long enough to reach the bottom of the page, this problem will show up. no matter how big the screen or what the resolution is. 

If everything is limited to the top part of the page where the bottom of the page is never reached, of course this problem will not show because the scroll bar won't show in that case, but however we cannot rule out of possibility of having longer form notes or larger photos that will push the content to the bottom page , which eventually will cause the scroll bar to show and then cause the shifting of the page. 

The solution remains, either having the scroll bar show all the time, or not showing at all, only by doing this you won't have the shifting caused by the sudden emergence of scroll bar, hope I explained myself clearly.

**Comment by jarodise** [comment]
Notice the scroll bar:
![Kapture 2020-08-14 at 12 21 11](https://user-images.githubusercontent.com/15899808/90276005-cbf34f80-de28-11ea-839c-9daeeeddc1ab.gif)

**Comment by binyamin** [comment]
Suggestion: If we move the popup away from the bottom of the screen, we might avoid the issue altogether.
![image](https://user-images.githubusercontent.com/39805353/90285459-f8679580-de41-11ea-90ac-ff23ddabfd6d.png)

I'm hesitant to have the scrollbar always present, because most websites don't act like that. I can't hide the scrollbar completely, because some pages would get cut off. That's why I'm looking for a workaround.

**Comment by binyamin** [comment]
@jarodise what do you think? :point_up:

**Comment by jarodise** [comment]
> @jarodise what do you think? ☝️

yeah, I think this is a good solution. 

another idea would be, having an on/off switch for preview popup, since this is the reason that's causing it.

**Comment by jarodise** [comment]
yes, it works for me! thanks for the effort!

**Comment by jarodise** [comment]
One last question: Do you know how I could apply the update on my forked repo?

**Comment by binyamin** [comment]
> One last question: Do you know how I could apply the update on my forked repo?

Great question. I'm really not sure. Template repositories are pretty new to me. I'd imagine you could connect your repository to this one using git. I'll play around.

**Comment by jarodise** [comment]
> > One last question: Do you know how I could apply the update on my forked repo?
> 
> Great question. I'm really not sure. Template repositories are pretty new to me. I'd imagine you could connect your repository to this one using git. I'll play around.

Yeah, if you find an easy option, please kindly let me know, I've played with a few git commands I found on stackoverflow, but came across some errors about merge conflict, as someone who's really not technical, I don't know how I could go forward with this, I hope I don't have to delete and refork the template every time you push an update. 

thanks!

**Comment by binyamin** [comment]
@jarodise I think I found a way for you to update it. Lmk if this works.

```sh
$ git remote add upstream git@github.com:binyamin/eleventy-garden.git
$ git stash
$ git merge upstream/master -m "Update template"
$ git stash apply
```
You may see merge conflicts (ie. lines of code which we both changed). VS code can help you resolve them.
