### ISSUE TITLE
Doesn't work with multi-word links

### ISSUE THREAD

**Issue by rithwik** [binyamin/eleventy-garden#21]
Trying to use my Obsidian vault to generate the garden. The .md files have multi word titles with spaces.

Clicking on the generated links doesn't work out of the box. I could fix this by replacing the spaces by hyphens in all the filenames. This makes the links work, but the backlink discovery still fails.

Example: Clicking on the link generated by [[Keep things simple]] doesn't work when the original filename is "Keep things simple.md". The link works after renaming file to "Keep-things-simple.md" but the backlink discovery doesn't.

**Comment by binyamin** [comment]
@rithwik Thanks for the heads-up. I will get to work on the backlink discovery. As for the filenames, I feel like most often a space in a filename is url-encoded. (Links, for example, use `%20` instead of a space).
