### ISSUE TITLE
Backlinks only appear if the page's filename is lowercase

### ISSUE THREAD

**Issue by SaysKez** [binyamin/eleventy-garden#26]
First up, thanks for putting this together! I've been wanting to try out Eleventy and this has been the perfect opportunity.

**Bug:**
I created a test digital garden based on the template and added some of my own existing notes. I noticed that backlinks for pages only show up if the page's filename is entirely lowercase.

**What happens:**
Example: note1 links to Note2 and vice versa. note1 shows Note2 in the backlinks section but Note2 does not show note1. This also happens when only one note links to the others.

Changing filenames to all lowercase fixes this. All links otherwise work as normal and it does not seem to matter if the actual link text contains uppercase characters as long as the filename it is linking to is lowercase.

**Notes:**
I'm running MacOS & viewing my local build in Chrome.

**Comment by binyamin** [comment]
Thanks for the heads up! And I appreciate the detailed bug report.

**Comment by SaysKez** [comment]
Removing `.toLowerCase()` from the link location: `// Extract link location
                    m.slice(2,-2).split("|")[0]
                        .toLowerCase()
                        .replace(/[^\w\s-]+/g,'')
                ));`

in the `notes.11tydata.js` file appears to fix the issue and display backlinks for files with uppercase characters (as long as they have no special characters or dashes).

**Comment by binyamin** [comment]
@SaysKez That makes sense. I'm getting the bug anyways, but I'll play around with it.
