### ISSUE TITLE
Question from a total noob

### ISSUE THREAD

**Issue by ScootRay** [binyamin/eleventy-garden#30]
I'd love to use this but I'm a total newbie and unsure how to work this.

Per your directions, I dropped my Obsidian files into the notes folder and ran NPM START but all I see is your sample site. How do I get it to process my own files and do I need to make an index of some sort? 

Thanks!
Ray

**Comment by binyamin** [comment]
I'm sorry that you're encountering issues. It's a bit difficult to debug issues without a reproducible test case, but here goes!
1. Did you run `npm install`?
2. I hope you didn't _replace_ the notes folder. There's one file, notes.11tydata.js, which needs to remain.
3. The notes are on a subpage (ie. localhost:8080 shows the main site. Notes are on localhost:8080/notes/)

**Comment by binyamin** [comment]
@ScootRay As this was a question as opposed to a bug/feature, I'm closing it. Feel free to start [a discussion](https://github.com/binyamin/eleventy-garden/discussions) if you still need help.
