### ISSUE TITLE
Preview not appear on hover 

### ISSUE THREAD

**Issue by francofaa** [binyamin/eleventy-garden#35]
**To Reproduce**
1. `npm start` in terminal in folder
2. In browser, navigate to "bar" page
3. Hover over link "Testing"
4. Testing preview is not visible. Also when navigating to Testing page, backlink to "bar" is not present

Forked repo here: https://github.com/francofaa/ArgotWiki/

**Expected behavior**
Preview should appear on hover on testing link. Backlink to bar should appear on testing page. 

**Environment (please complete the following information):**
 - OS & Version: Mac OS 10.15.7
 - Browser FF 82.0

**Comment by binyamin** [comment]
Thanks for opening the issue. I'm in middle of debugging this.

**Comment by binyamin** [comment]
Okay, I found the problem. It was expecting a period, in order to construct the preview.
