### ISSUE TITLE
List of backlinks are not reported in new MD files 

### ISSUE THREAD

**Issue by ronykris** [binyamin/eleventy-garden#38]
**Describe the bug**
I have created a set of new notes with wikiinks. The list of reference pages of the note I'm in is not getting computed and displayed in the backlinks section of the page. 

**To Reproduce**
1. Go to 'https://epic-johnson-6b6441.netlify.app/notes/easter%20egg/' 
2. Click on 'Random Notes' in the backlinks section. 
3. List of backlinks in the backlink section below is empty. It says no backlinks found even though the page I'm in has backlinks. 

**Expected behavior**
I expect to see a list reference pages of the note I'm in, in the backlinks section of the page. 

**Environment (please complete the following information):**
 - OS & Version: windows 10
 - Browser : chrome

**Additional context**
Refer this sample link
https://epic-johnson-6b6441.netlify.app/notes/easter%20egg/

**Comment by binyamin** [comment]
I can't find any pages linking to `/notes/random-notes` or `/notes/subnotes/random-notes`. The backlinks section is just a list of all notes which contain a link to the current page.

**Comment by binyamin** [comment]
@ronykris I'm closing this, since you haven't responded. If you have further information, feel free to reopen it.
