### ISSUE TITLE
Syntax highlight prism

### ISSUE THREAD

**Issue by erwinlauener** [binyamin/eleventy-garden#81]
I can't implement eleventy's syntax highlight 'prism' into the .eleventy.js file without bugs. Help is needed. 🙏🏻

**Comment by binyamin** [comment]
What bugs are you seeing?

**Comment by erwinlauener** [comment]
Hi Aron

Error: EleventyConfig.addPlugin expects the first argument to be a function.

I tried to correct the .eleventy.js, but another errors appeared. Im on an old MacOS (10.11.6) Maybe the installation of the syntax highlight plugin isn’t as it should be…
However, thanks for your answer

Erwin

**Comment by binyamin** [comment]
@erwinlauener I'm closing this issue, since it's not related to the template itself.

I recommend asking on [Eleventy's discord server](https://www.11ty.dev/blog/discord/) or opening a discussion on the [ main repo's GitHub discussions](https://github.com/11ty/eleventy/discussions).
