### ISSUE TITLE
Notes graph

### ISSUE THREAD

**Issue by xplosionmind** [binyamin/eleventy-garden#83]
**Is your feature request related to a problem? Please describe.**
Graphically representing links among notes.

**Describe the solution you'd like**
Display a graph of all links among notes.

**Describe alternatives you've considered**
none

**Additional context**
- my specific needs: xplosionmind/tommi.space#8
- example of a wonderful plugin, for Jekyll: [jekyll-graph](https://github.com/manunamz/jekyll-graph)

**Comment by binyamin** [comment]
I think this would work well as a separate plugin and/or tutorial. I think it's too complex for this template. People should be able to understand the code, so they can customize it. For more info, see https://github.com/binyamin/eleventy-garden/discussions/71#discussion-3765981
