### ISSUE TITLE
Backlinks behave differently in local and on github page

### ISSUE THREAD

**Issue by jrekier** [binyamin/eleventy-garden#87]
**Describe the bug**
The expected backlink appears in local (image 1), but not when pushed to my (project) github page. Interestingly, another backlink appears in that case (image 2). 

**Screenshots**
![image](https://user-images.githubusercontent.com/9407736/176148162-2381f740-9585-4160-8315-b096057be576.png)
![image](https://user-images.githubusercontent.com/9407736/176148344-95edc200-aede-4b64-9343-771b42074348.png)

**Additional context**
My page contains two notes named "First note" and "Inertial Waves and Inertial Modes" that both link to a third note named "Poincaré equation". Only the first note appears in the list of backlinks online. On the other hand, only the second appears in local. That does not seem to be collections issue. I could not find the reason for this behavior.

**Comment by binyamin** [comment]
I assume that it's related to how the GitHub Pages site exists in a sub-directory. Unfortunately, I have no idea what's going on. If you could create a minimal test-case, that might help me debug this.

Also, I recently made an Eleventy _plugin_ which encapsulates this template's logic. Maybe it will work differently. It just plugs into an existing eleventy site. https://github.com/binyamin/eleventy-plugin-backlinks

**Comment by binyamin** [comment]
@jrekier Yeah, I guess you would need a GitHub page to go with it. If you can do that, it would be great.

**Comment by jrekier** [comment]
Hi @binyamin,

I'm finally getting back to this. I haven't had time to build a GitHub page from the ground up, but I think you should be able to reproduce the issue using my actual page: https://github.com/jrekier/mind-garden 

I have tried to look at your plugin but I'm having difficulty with the practical implementation.

Thanks for your help,
